# Generated by Django 3.2.12 on 2022-02-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canva_img', models.ImageField(upload_to='canva-img')),
                ('canva_title', models.CharField(max_length=250)),
                ('canva_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_image', models.ImageField(upload_to='pro-img')),
                ('pro_title', models.CharField(max_length=250)),
                ('pro_desc', models.TextField()),
            ],
        ),
    ]
